export interface MenuItem {
  name: string
  price: string | { small?: string; large?: string }
  description?: string
}

export interface MenuCategory {
  id: string
  title: string
  icon: string
  items: MenuItem[]
}

export const menuData: MenuCategory[] = [
  {
    id: "appetizers",
    title: "Appetizers & Salads",
    icon: "🥗",
    items: [
      { name: "Samosa Chaat", price: "RM10" },
      { name: "Chana Chaat", price: "RM8" },
      { name: "Samosa", price: "RM2" },
      { name: "Vege Salad", price: "RM7" },
      { name: "Yogurt Salad", price: "RM8" },
    ],
  },
  {
    id: "rolls",
    title: "Rolls (Paratha/Chapati)",
    icon: "🥙",
    items: [
      { name: "Chicken Tikka Botti Roll", price: { small: "RM11", large: "RM14" } },
      { name: "Chicken Tikka Botti Roll with Fries", price: { small: "RM14", large: "RM17" } },
      { name: "Chicken Malai Botti Roll", price: { small: "RM11", large: "RM14" } },
      { name: "Chicken Malai Botti Roll with Fries", price: { small: "RM14", large: "RM17" } },
      { name: "Chicken Tandoori Botti Roll", price: { small: "RM11", large: "RM14" } },
      { name: "Chicken Tandoori Botti Roll with Fries", price: { small: "RM14", large: "RM17" } },
      { name: "Chicken Turkish Botti Roll", price: { small: "RM11", large: "RM14" } },
      { name: "Chicken Turkish Botti Roll with Fries", price: { small: "RM14", large: "RM17" } },
      { name: "Chicken Reshmi Kabab Roll", price: { small: "RM11", large: "RM14" } },
      { name: "Chicken Reshmi Kabab Roll with Fries", price: { small: "RM14", large: "RM17" } },
      { name: "Chicken Shawarma Roll", price: { small: "RM11", large: "RM14" } },
      { name: "Chicken Shawarma Roll with Fries", price: { small: "RM14", large: "RM17" } },
      { name: "Chicken Zinger Roll", price: { small: "RM11", large: "RM14" } },
      { name: "Chicken Zinger Roll with Fries", price: { small: "RM14", large: "RM17" } },
      { name: "Beef Seekh Kabab Roll", price: { small: "RM13", large: "RM17" } },
      { name: "Beef Seekh Kabab Roll with Fries", price: { small: "RM16", large: "RM19" } },
      { name: "Beef Behari Botti Roll", price: { small: "RM13", large: "RM16" } },
      { name: "Beef Behari Botti Roll with Fries", price: { small: "RM16", large: "RM19" } },
      { name: "Beef Chaply Kebab Roll", price: { small: "RM11", large: "RM14" } },
      { name: "Beef Chaply Kebab Roll with Fries", price: { small: "RM14", large: "RM17" } },
      { name: "Shami Kebab Roll", price: { small: "RM11", large: "RM14" } },
      { name: "Shami Kebab Roll with Fries", price: { small: "RM14", large: "RM17" } },
    ],
  },
  {
    id: "biryani",
    title: "Biryanis with BBQ Items",
    icon: "🍛",
    items: [
      { name: "Mutton Biryani", price: "RM16" },
      { name: "Beef Biryani", price: "RM15" },
      { name: "Chicken Biryani", price: "RM13" },
      { name: "Vege Biryani", price: "RM10" },
      { name: "Biryani Rice with Shami Kebab", price: "RM14" },
      { name: "Biryani Rice with Beef Chaply Kebab", price: "RM14" },
      { name: "Biryani Rice with Potato Cutlet", price: "RM12" },
      { name: "Biryani Rice", price: "RM7" },
      { name: "Biryani Rice with Egg", price: "RM10" },
      { name: "Chicken Chop with Biryani Rice", price: "RM16" },
      { name: "Chicken Tikka with Biryani Rice", price: "RM16" },
      { name: "Chicken Tikka Botti with Biryani Rice", price: "RM16" },
      { name: "Chicken Malai Botti with Biryani Rice", price: "RM16" },
      { name: "Chicken Turkish Botti with Biryani Rice", price: "RM16" },
      { name: "Chicken Reshmi Kabab with Biryani Rice", price: "RM16" },
      { name: "Biryani Rice with Beef Seekh Kabab", price: "RM18" },
      { name: "Biryani Rice with Beef Behari Botti", price: "RM18" },
      { name: "Biryani Rice with Beef Gola Kabab", price: "RM18" },
      { name: "Biryani Rice with Beef Cheese Gola Kabab", price: "RM21" },
      { name: "Biryani Rice with Chicken Gola Kabab", price: "RM16" },
      { name: "Biryani Rice with Chicken Cheese Gola Kabab", price: "RM19" },
      { name: "Mix Grilled with Biryani Rice", price: "RM27" },
    ],
  },
  {
    id: "pulao",
    title: "Pulao Rice with BBQ Items",
    icon: "🍚",
    items: [
      { name: "Beef Afghani Pulao", price: "RM15" },
      { name: "Pulao Rice with Shami Kebab", price: "RM14" },
      { name: "Pulao Rice with Beef Chaply Kebab", price: "RM14" },
      { name: "Pulao Rice with Potato Cutlet", price: "RM12" },
      { name: "Pulao Rice", price: "RM7" },
      { name: "Pulao Rice with Chicken Chop", price: "RM16" },
      { name: "Pulao Rice with Chicken Tikka", price: "RM16" },
      { name: "Pulao Rice with Chicken Tikka Botti", price: "RM16" },
      { name: "Pulao Rice with Chicken Malai Botti", price: "RM16" },
      { name: "Pulao Rice with Chicken Tandoori Botti", price: "RM16" },
      { name: "Pulao Rice with Chicken Reshmi Kabab", price: "RM16" },
      { name: "Pulao Rice with Turkish Botti", price: "RM16" },
      { name: "Pulao Rice with Beef Behari Botti", price: "RM18" },
      { name: "Pulao Rice with Beef Seekh Kabab", price: "RM18" },
      { name: "Pulao Rice with Beef Gola Kabab", price: "RM18" },
      { name: "Pulao Rice with Beef Cheese Gola Kabab", price: "RM21" },
      { name: "Pulao Rice with Chicken Gola Kabab", price: "RM16" },
      { name: "Pulao Rice with Chicken Cheese Gola Kabab", price: "RM19" },
      { name: "Mix Grilled BBQ with Pulao Rice", price: "RM27" },
    ],
  },
  {
    id: "bbq-paratha",
    title: "BBQ Items with Paratha",
    icon: "🍖",
    items: [
      { name: "Chicken Tikka with Paratha", price: "RM15" },
      { name: "Chicken Tikka Botti with Paratha", price: "RM15" },
      { name: "Chicken Malai Botti with Paratha", price: "RM15" },
      { name: "Chicken Turkish Botti with Paratha", price: "RM15" },
      { name: "Chicken Tandoori Botti with Paratha", price: "RM15" },
      { name: "Chicken Reshmi Kabab with Paratha", price: "RM15" },
      { name: "Beef Behari Botti with Paratha", price: "RM17" },
      { name: "Beef Seekh Kabab with Paratha", price: "RM16" },
      { name: "Mix Grilled BBQ with Paratha", price: "RM27" },
    ],
  },
  {
    id: "bbq-fries",
    title: "BBQ with Fries",
    icon: "🍟",
    items: [
      { name: "Chicken Tikka with Fries", price: "RM15" },
      { name: "Chicken Tikka Botti with Fries", price: "RM14" },
      { name: "Chicken Malai Botti with Fries", price: "RM14" },
      { name: "Chicken Tandoori Botti with Fries", price: "RM14" },
      { name: "Chicken Turkish Botti with Fries", price: "RM14" },
      { name: "Chicken Reshmi Kabab with Fries", price: "RM14" },
      { name: "Beef Seekh Kabab with Fries", price: "RM16" },
      { name: "Beef Behari Botti with Fries", price: "RM16" },
      { name: "Beef Chaply Kebab with Fries", price: "RM11" },
      { name: "Shami Kebab with Fries", price: "RM11" },
      { name: "Mix Grilled with Fries", price: "RM27" },
      { name: "Chicken Chop with Fries", price: "RM15" },
    ],
  },
  {
    id: "sides",
    title: "Sides & Snacks",
    icon: "🍴",
    items: [
      { name: "Chicken Nuggets with Fries", price: "RM11" },
      { name: "Chicken Nuggets with Masalah Fries", price: "RM12" },
      { name: "Only Nuggets", price: "RM11" },
      { name: "Fish Nuggets with Fries", price: "RM12" },
      { name: "Fish Nuggets with Masalah Fries", price: "RM13" },
      { name: "Only Fish Nuggets", price: "RM13" },
      { name: "Masalah Fries", price: "RM8" },
      { name: "Plain Fries", price: "RM7" },
      { name: "Beef Chaply Kebab", price: "RM7" },
      { name: "Shami Kebab", price: "RM7" },
      { name: "Potato Cutlet", price: "RM5" },
    ],
  },
  {
    id: "fried-rice",
    title: "Fried Rice",
    icon: "🍜",
    items: [
      { name: "Chicken Manchurian with Fried Rice", price: "RM16" },
      { name: "Chicken Fried Rice", price: "RM9" },
      { name: "Mutton Fried Rice", price: "RM12" },
      { name: "Beef Fried Rice", price: "RM10" },
      { name: "Vege Fried Rice", price: "RM6" },
      { name: "Egg Fried Rice", price: "RM5" },
      { name: "Plain Rice", price: "RM2.50" },
    ],
  },
  {
    id: "pasta",
    title: "Pasta",
    icon: "🍝",
    items: [
      { name: "Chicken Macaroni", price: "RM11" },
      { name: "Chicken Cheese Macaroni", price: "RM13" },
      { name: "Extra Chicken and Cheese Macaroni", price: "RM17" },
      { name: "Vege Macaroni with Cheese", price: "RM10" },
      { name: "Chicken Spaghetti", price: "RM11" },
      { name: "Chicken Cheese Spaghetti", price: "RM13" },
      { name: "Extra Chicken Cheese Spaghetti", price: "RM17" },
      { name: "Vege Spaghetti with Cheese", price: "RM10" },
    ],
  },
  {
    id: "vegetarian",
    title: "Vegetarian Curries",
    icon: "🥬",
    items: [
      { name: "Mix Vege", price: "RM8" },
      { name: "Achari Mix Vege", price: "RM10" },
      { name: "Potato Masala", price: "RM8" },
      { name: "Potato with Egg Curry", price: "RM8" },
      { name: "Egg Curry", price: "RM8" },
      { name: "Rajma Daal", price: "RM8" },
      { name: "Maash Daal", price: "RM8" },
      { name: "Chana Masalah", price: "RM8" },
      { name: "Achari Chana Masalah", price: "RM10" },
      { name: "Chana Masalah with Egg", price: "RM10" },
    ],
  },
  {
    id: "non-vegetarian",
    title: "Non-Vegetarian Curries",
    icon: "🍲",
    items: [
      { name: "Mutton Karahi", price: "RM16" },
      { name: "Mutton Handi", price: "RM18" },
      { name: "Mutton Potato Masala", price: "RM17" },
      { name: "Beef Qeema", price: "RM15" },
      { name: "Beef Qeema with Potato", price: "RM16" },
      { name: "Beef Karahi", price: "RM15" },
      { name: "Beef Achari", price: "RM16" },
      { name: "Beef Potato Masala", price: "RM15" },
      { name: "Special Chicken Karahi", price: "RM15" },
      { name: "Butter Chicken", price: "RM13" },
      { name: "Chicken Qeema with Potato", price: "RM14" },
      { name: "Chicken Achari", price: "RM14" },
      { name: "Chicken Tikka Masalah", price: "RM15" },
    ],
  },
  {
    id: "breads",
    title: "Breads & Parathas",
    icon: "🫓",
    items: [
      { name: "Chicken Paratha", price: "RM10" },
      { name: "Chicken Cheese Paratha", price: "RM12" },
      { name: "Extra Chicken Cheese Paratha", price: "RM14" },
      { name: "Potato Paratha", price: "RM8" },
      { name: "Potato Cheese Paratha", price: "RM10" },
      { name: "Potato Onion Cheese Paratha", price: "RM11" },
      { name: "Cheese Paratha", price: "RM8" },
      { name: "Extra Cheese Paratha", price: "RM10" },
      { name: "Butter Paratha", price: "RM5" },
      { name: "Plain Paratha", price: "RM4" },
      { name: "Butter Chapati", price: "RM4" },
      { name: "Plain Chapati", price: "RM3" },
      { name: "Big Chapati", price: "RM4" },
      { name: "Astori Paratha", price: "RM4" },
      { name: "Egg Omelette", price: "RM7" },
      { name: "Egg Fried", price: "RM2.50" },
    ],
  },
  {
    id: "sandwiches",
    title: "Sandwiches",
    icon: "🥪",
    items: [
      { name: "Club Sandwich", price: "RM15" },
      { name: "Chicken Sandwich", price: "RM10" },
      { name: "Chicken Cheese Sandwich", price: "RM11" },
      { name: "Chicken Shami Kebab Sandwich with Fries", price: "RM11", description: "Grilled" },
      { name: "Chicken Shami Kebab with Cheese Sandwich + Fries", price: "RM13", description: "Grilled" },
      { name: "Chicken Sandwich with Fries", price: "RM10", description: "Grilled" },
      { name: "Chicken Cheese Sandwich with Fries", price: "RM11", description: "Grilled" },
      { name: "Chicken Cheese Egg Sandwich with Fries", price: "RM13", description: "Grilled" },
      { name: "Potato Sandwich with Fries", price: "RM8", description: "Grilled" },
      { name: "Potato Cheese Sandwich with Fries", price: "RM10", description: "Grilled" },
    ],
  },
  {
    id: "burgers",
    title: "Burgers",
    icon: "🍔",
    items: [
      { name: "Large Zinger Burger with Fries", price: "RM17" },
      { name: "Regular Chicken Zinger Burger with Fries", price: "RM13" },
      { name: "Chicken Burger + Fries", price: "RM10" },
      { name: "Beef Burger + Fries", price: "RM10" },
      { name: "Chicken Cheese Burger + Fries", price: "RM12" },
      { name: "Beef Cheese Burger + Fries", price: "RM12" },
      { name: "Egg Burger with Fries", price: "RM8" },
      { name: "Egg Cheese Burger with Fries", price: "RM9" },
      { name: "Potato Burger with Fries", price: "RM8" },
    ],
  },
  {
    id: "beverages",
    title: "Beverages",
    icon: "🥤",
    items: [
      { name: "Vanilla Milkshake", price: "RM9" },
      { name: "Chocolate Milkshake", price: "RM9" },
      { name: "Mango Milkshake", price: "RM9" },
      { name: "Mango Lassi", price: "RM10" },
      { name: "Sweet Lassi", price: "RM8" },
      { name: "Salted Lassi", price: "RM8" },
      { name: "Pak Tea", price: "RM5" },
      { name: "Duodh Patty", price: "RM7" },
      { name: "Ginger Tea", price: "RM3" },
      { name: "Mint Tea", price: "RM3" },
      { name: "Masalah Tea", price: "RM6" },
      { name: "Sprite", price: "RM2.50" },
      { name: "Coke Zero", price: "RM2.50" },
      { name: "Coke", price: "RM2.50" },
      { name: "Fanta", price: "RM2.50" },
    ],
  },
]
